title: My blog page
author: HallofPool
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  I'm world wide!  Got my first Unity project to run and trying to publish the WebGL to this blog so everyone
  can see this grarly project.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  hallofpool # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
